INCLUDES = -I../UsageEnvironment/include -I../groupsock/include -I../liveMedia/include -I../BasicUsageEnvironment/include -I../../dep/boost -I../../dep/fifi/src -I../../dep/sak/src -I../../dep/kodo -pthread
##### Change the following for your environment: 
